kind: pipeline
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet test --configuration Release --no-build --verbosity normal --filter Category!=Runtime

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - dotnet publish --configuration Release --output ./publish

trigger:
  branch:
  - prod
  event:
  - pull_request
  - push
