version: '3.9'

# TODO: Разделить сервисы в отдельные файлы.
# TODO: Продумать сети

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./5. Init Database:/docker-entrypoint-initdb.d
      - npg-data:/var/lib/postgresql/data
    ports:
      - "5443:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  
# TestsManager
  beaverstests.testsmanager.api:
    container_name: beaverstests.testsmanager.api
    image: beaverstests.testsmanager.api
    build:
      context: ../.
      dockerfile: src/Services/TestsManager/BeaversTests.TestsManager.Api/Dockerfile
    ports:
      - "5174:5174"
    environment:
      ASPNETCORE_URLS: http://+:5174
      ASPNETCORE_HTTP_PORT: 5174
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TestManagerNpgsql: Server=postgres:5432;Database=BeaversTests.TestsManager;Username=postgres;Password=qwerty123
      ConnectionStrings__EventStoreNpgsql: Server=postgres:5432;Database=BeaversTests.TestsManager.EventStore;Username=postgres;Password=qwerty123
      TestDriversDirectory: drivers
      S3__Minio__Endpoint: minio:9000
      S3__Minio__AccessKey: kirill
      S3__Minio__SecretKey: minio123
      S3__Minio__UseSSL: false
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: rmuser
      RabbitMQ__Password: rmpassword
      RabbitMQ__Exchange__Name: beaverstests.testsmanager
      RabbitMQ__Retries: 10
      RabbitMQ__RetryTimeoutMilliseconds: 10000
      Logging__LogLevel__Default: Debug
    depends_on:
      - minio
      - postgres
      - rabbitmq

# TODO: test this, add testRunnerAgent services
# TestRunnerController
  
  beaverstests.testrunnercontroller.api:
    container_name: beaverstests.testrunnercontroller.api
    image: beaverstests.testrunnercontroller.api
    build:
      context: ../.
      dockerfile: src/Services/TestRunnerController/BeaversTests.TestRunnerController.Api/Dockerfile
    ports:
      - "5175:5175"
    environment:
      ASPNETCORE_URLS: http://+:5175
      ASPNETCORE_HTTP_PORT: 5175
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TestRunnerControllerNpgsqlRead: Server=postgres:5432;Database=BeaversTests.TestRunnerController;Username=postgres;Password=qwerty123
      ConnectionStrings__EventStoreNpgsql: Server=postgres:5432;Database=BeaversTests.TestRunnerController.EventStore;Username=postgres;Password=qwerty123
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: rmuser
      RabbitMQ__Password: rmpassword
      RabbitMQ__Exchange__Name: beaverstests.testsmanager
      RabbitMQ__Retries: 10
      RabbitMQ__RetryTimeoutMilliseconds: 10000
      Logging__LogLevel__Default: Debug
    depends_on:
      - minio
      - postgres
      - rabbitmq

# Shared services
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "kirillgroshev52@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5400:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: kirill
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  npg-data:
    driver: local
  pgadmin-data: