<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Blocks\Auth\BeaversTests.Auth.AspNetCore.Shared\BeaversTests.Auth.AspNetCore.Shared.csproj" />
      <ProjectReference Include="..\..\..\Blocks\Auth\BeaversTests.Auth.Bundle\BeaversTests.Auth.Bundle.csproj" />
      <ProjectReference Include="..\BeaversTests.Manager.Api\BeaversTests.Manager.Api.csproj" />
      <ProjectReference Include="..\BeaversTests.Manager.Persistence\BeaversTests.Manager.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
      <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
      <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

</Project>
