<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\BeaversTests.Common.S3\BeaversTests.Common.S3.csproj" />
      <ProjectReference Include="..\BeaversTests.TestRunnerAgent.App\BeaversTests.TestRunnerAgent.App.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    </ItemGroup>

</Project>
