<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="NUnit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BeaversTests.S3.MinioProvider\BeaversTests.S3.MinioProvider.csproj" />
    </ItemGroup>

</Project>
