<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\BeaversTests.Common.Application\BeaversTests.Common.Application.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\BeaversTests.Common.CQRS\BeaversTests.Common.CQRS.csproj" />
      <ProjectReference Include="..\..\..\Events\BeaversTests.TestRunnerAgent.Events\BeaversTests.TestRunnerAgent.Events.csproj" />
      <ProjectReference Include="..\BeaversTests.TestRunnerController.Core\BeaversTests.TestRunnerController.Core.csproj" />
    </ItemGroup>

</Project>
