<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BeaversTests.Isolation.Contract\BeaversTests.Isolation.Contract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Docker.DotNet" />
    </ItemGroup>

</Project>
