<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\BeaversTests.Common.CQRS.Abstractions\BeaversTests.Common.CQRS.Abstractions.csproj" />
      <ProjectReference Include="..\..\..\Events\BeaversTests.TestRunnerAgent.Events\BeaversTests.TestRunnerAgent.Events.csproj" />
      <ProjectReference Include="..\..\..\Events\BeaversTests.TestRunnerController.Events\BeaversTests.TestRunnerController.Events.csproj" />
      <ProjectReference Include="..\..\..\Events\BeaversTests.TestsManager.Events\BeaversTests.TestsManager.Events.csproj" />
    </ItemGroup>

</Project>
